#!/usr/bin/python3
"""Pure deterministic generator for a pristine direct-reference request.

The generated OCaml source is still raw and unauthenticated.  This module does
not write the source, start OCaml/HOL Light, collect output, construct coverage
or a candidate, or approve any release gate.  A later fixed-source collector
must authenticate this generator, its protocol sibling, every input and the
exact generated bytes before executing them in a fresh isolated process.
"""

from __future__ import annotations

import copy
import hashlib
import re
from pathlib import PurePosixPath
from types import ModuleType
from typing import Any


REQUEST_SOURCE_PATH = "request.ml"
EXPECTED_PROTOCOL_SCHEMA = 3
EXPECTED_PLAN_KIND = "candle-flyspeck-pristine-direct-reference-raw-plan-v3"
EXPECTED_REQUEST_KIND = "candle-flyspeck-pristine-direct-reference-request-v3"
EXPECTED_MARKER_PROTOCOL = (
    "candle-flyspeck-pristine-direct-reference-markers-v3"
)
EXPECTED_BOUNDARY_ID = "07-final_assembly-through-296"
EXPECTED_ACTION_COUNT = 297
EXPECTED_LP_WRAPPER_AFTER = 177
EXPECTED_LP_VERIFY_ACTION = 183
EXPECTED_LP_CONSUMER_ACTION = 184
EXPECTED_SERIALIZER_SOURCE = "candle:candle/fingerprint.ml"
EXPECTED_FINAL_TARGET_SOURCE = "candle:candle/flyspeck_l2_target.ml"
EXPECTED_THEOREM_NAMES = (
    "Linear_programming_results.linear_programming_results_th",
    "Mk_all_ineq.the_nonlinear_inequalities",
    "The_kepler_conjecture.tame_nonlinear_imp_kepler_conjecture",
    "Candle_flyspeck_l2.tame_imp_kepler_conjecture",
)
EXPECTED_MARKER_CONTRACT = {
    "protocol": EXPECTED_MARKER_PROTOCOL,
    "session_start": "CANDLE_PRISTINE_DIRECT_REFERENCE_START_V3",
    "native_load": "CANDLE_PRISTINE_DIRECT_NATIVE_LOAD_V3",
    "action_complete": "CANDLE_PRISTINE_DIRECT_ACTION_COMPLETE_V3",
    "lp_success": "CANDLE_PRISTINE_DIRECT_LP_SUCCESS_V3",
    "semantic_observation": "CANDLE_PRISTINE_DIRECT_SEMANTIC_V3",
    "session_complete": "CANDLE_PRISTINE_DIRECT_REFERENCE_COMPLETE_V3",
    "nonce_in_every_marker": True,
}
SOURCE_INVENTORY_KIND = (
    "candle-flyspeck-authenticated-original-source-inventory-v1"
)
SOURCE_INVENTORY_POLICY = "exact-400-plan-bindings-with-candle-selection-v1"

HEX64 = re.compile(r"[0-9a-f]{64}")
HEX32 = re.compile(r"[0-9a-f]{32}")
LOGICAL_KEY = re.compile(r"(?:candle|flyspeck):[A-Za-z0-9_./+@-]+")
THEOREM_VALUE = re.compile(r"[A-Z][A-Za-z0-9_]*(?:\.[a-z][A-Za-z0-9_]*)+")


class RequestGenerationError(ValueError):
    """The pure generator input is incompatible or cannot be rendered."""


def require(condition: bool, message: str) -> None:
    if not condition:
        raise RequestGenerationError(message)


_PROTOCOL: ModuleType | None = globals().get("_TRUSTED_PROTOCOL_MODULE_INPUT")


def _canonical_bytes(value: Any) -> bytes:
    try:
        import json

        return json.dumps(
            value, sort_keys=True, separators=(",", ":"), allow_nan=False,
        ).encode("utf-8")
    except (TypeError, ValueError) as error:
        raise RequestGenerationError(f"malformed exact JSON: {error}") from error


def _exact(value: Any, expected: Any, label: str) -> None:
    require(_canonical_bytes(value) == _canonical_bytes(expected),
            f"exact {label} mismatch")


def _protocol() -> ModuleType:
    module = _PROTOCOL
    require(isinstance(module, ModuleType),
            "fixed pristine-reference protocol activation is required")
    require(
        getattr(module, "RAW_PROTOCOL_SCHEMA", None) == EXPECTED_PROTOCOL_SCHEMA and
        getattr(module, "PLAN_KIND", None) == EXPECTED_PLAN_KIND and
        getattr(module, "REQUEST_KIND", None) == EXPECTED_REQUEST_KIND and
        getattr(module, "MARKER_PROTOCOL", None) == EXPECTED_MARKER_PROTOCOL and
        getattr(module, "FINAL_BOUNDARY_ID", None) == EXPECTED_BOUNDARY_ID and
        getattr(module, "FINAL_ACTION_COUNT", None) == EXPECTED_ACTION_COUNT and
        getattr(module, "LP_WRAPPER_AFTER_ACTION_INDEX", None) ==
        EXPECTED_LP_WRAPPER_AFTER and
        getattr(module, "LP_VERIFY_ACTION_INDEX", None) ==
        EXPECTED_LP_VERIFY_ACTION and
        getattr(module, "LP_CONSUMER_ACTION_INDEX", None) ==
        EXPECTED_LP_CONSUMER_ACTION and
        getattr(module, "SERIALIZER_SOURCE", None) ==
        EXPECTED_SERIALIZER_SOURCE and
        getattr(module, "FINAL_TARGET_SOURCE", None) ==
        EXPECTED_FINAL_TARGET_SOURCE and
        tuple(getattr(module, "FINAL_THEOREM_NAMES", ())) ==
        EXPECTED_THEOREM_NAMES,
        "incompatible pristine-reference protocol sibling",
    )
    _exact(getattr(module, "MARKER_CONTRACT", None), EXPECTED_MARKER_CONTRACT,
           "pristine marker contract")
    return module


def _hex(value: object, pattern: re.Pattern[str], label: str) -> str:
    require(isinstance(value, str) and pattern.fullmatch(value) is not None,
            f"malformed {label}")
    return value


def _safe_relative(value: object, label: str) -> str:
    require(isinstance(value, str) and value and "\\" not in value and
            all(32 <= ord(character) <= 126 for character in value),
            f"malformed {label}")
    path = PurePosixPath(value)
    require(not path.is_absolute() and path.as_posix() == value and
            all(part not in {"", ".", ".."} for part in path.parts),
            f"unsafe {label}")
    return value


def _validate_execution_selection(value: object, label: str) -> bool:
    require(isinstance(value, dict), f"malformed {label}")
    if value.get("mode") == "original-source":
        require(set(value) == {"mode"}, f"malformed {label}")
        return False
    require(set(value) == {
                "mode", "id", "kind", "normalized_bytes",
                "normalized_sha256", "normalized_md5", "operation_count",
            } and value.get("mode") == "candle-normalization-bound" and
            value.get("kind") == "exact_bytes_replace_sequence" and
            isinstance(value.get("id"), str) and value["id"] and
            all(32 <= ord(character) <= 126 for character in value["id"]) and
            type(value.get("normalized_bytes")) is int and
            value["normalized_bytes"] > 0 and
            type(value.get("operation_count")) is int and
            value["operation_count"] > 0,
            f"malformed {label}")
    _hex(value.get("normalized_sha256"), HEX64,
         f"{label} normalized SHA-256")
    _hex(value.get("normalized_md5"), HEX32, f"{label} normalized MD5")
    return True


def _validate_source_inventory(
    value: object, plan: dict[str, Any], protocol: ModuleType,
) -> list[dict[str, Any]]:
    fields = {
        "schema", "kind", "policy", "record_count",
        "normalization_binding_count", "ordered_record_sha256", "records",
    }
    require(isinstance(value, dict) and set(value) == fields and
            type(value.get("schema")) is int and value["schema"] == 1 and
            value.get("kind") == SOURCE_INVENTORY_KIND and
            value.get("policy") == SOURCE_INVENTORY_POLICY and
            type(value.get("record_count")) is int and
            value["record_count"] == 400 and
            type(value.get("normalization_binding_count")) is int and
            0 < value["normalization_binding_count"] < 400,
            "malformed request-generator source inventory")
    records = value.get("records")
    require(isinstance(records, list) and len(records) == 400,
            "request-generator source inventory is not exactly 400 records")
    previous_key: str | None = None
    identities: set[tuple[str, str]] = set()
    result: list[dict[str, Any]] = []
    normalization_count = 0
    for index, record in enumerate(records):
        require(isinstance(record, dict) and set(record) == {
                    "index", "key", "repository", "path", "original_bytes",
                    "original_sha256", "original_md5",
                    "candle_plan_execution_selection",
                } and type(record.get("index")) is int and
                record["index"] == index and
                record.get("repository") in {"candle", "flyspeck"} and
                type(record.get("original_bytes")) is int and
                record["original_bytes"] > 0,
                f"malformed request-generator source record: {index}")
        key = record.get("key")
        path = _safe_relative(record.get("path"), f"source path {index}")
        require(isinstance(key, str) and LOGICAL_KEY.fullmatch(key) is not None and
                key == f"{record['repository']}:{path}" and
                (previous_key is None or previous_key < key),
                f"source key/order mismatch: {index}")
        previous_key = key
        sha256 = _hex(record.get("original_sha256"), HEX64,
                      f"source SHA-256 {index}")
        md5 = _hex(record.get("original_md5"), HEX32, f"source MD5 {index}")
        normalization_count += _validate_execution_selection(
            record.get("candle_plan_execution_selection"),
            f"source execution selection {index}",
        )
        basename = PurePosixPath(path).name
        identity = (basename, md5)
        require(identity not in identities,
                f"ambiguous stock loader identity: {basename}/{md5}")
        identities.add(identity)
        result.append({
            "logical_source": key,
            "basename": basename,
            "bytes": record["original_bytes"],
            "sha256": sha256,
            "md5": md5,
        })
    require(value.get("ordered_record_sha256") ==
            protocol.canonical_sha256(records) and
            normalization_count == value["normalization_binding_count"],
            "request-generator source inventory digest mismatch")
    inventory_authority = plan["authority"]["inputs"]["source_inventory"]
    _exact(
        protocol.content_record(value),
        {
            "bytes": inventory_authority["bytes"],
            "sha256": inventory_authority["sha256"],
        },
        "source inventory versus plan authority",
    )
    required = {
        protocol.HOL_LIGHT_SOURCE,
        protocol.STRICTBUILD_SOURCE,
        protocol.FINAL_TARGET_SOURCE,
        *(record["selected_source"] for record in plan["actions"]["records"]),
    }
    actual = {record["logical_source"] for record in result}
    require(required <= actual,
            "source inventory omits a required pristine execution source")
    inventory_by_key = {record["key"]: record for record in records}
    for index, action in enumerate(plan["actions"]["records"]):
        source = inventory_by_key[action["selected_source"]]
        _exact(
            {
                field: action[field] for field in (
                    "original_bytes", "original_sha256", "original_md5",
                    "candle_plan_execution_selection",
                )
            },
            {
                field: source[field] for field in (
                    "original_bytes", "original_sha256", "original_md5",
                    "candle_plan_execution_selection",
                )
            },
            f"action {index} versus source inventory",
        )
    final = inventory_by_key[protocol.FINAL_TARGET_SOURCE]
    final_authority = plan["authority"]["inputs"]["final_target"]
    _exact(
        {field: final[field] for field in ("original_bytes", "original_sha256")},
        {
            "original_bytes": final_authority["bytes"],
            "original_sha256": final_authority["sha256"],
        },
        "final target versus source inventory",
    )
    return result


def _ocaml_string(value: str) -> str:
    require(isinstance(value, str) and all(
                character not in {"\x00", "\r", "\n"} for character in value
            ), "OCaml literal contains a forbidden character")
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    escaped = escaped.replace("\t", "\\t").replace("\b", "\\b")
    return f'"{escaped}"'


def _line_call(name: str, fields: list[str]) -> str:
    expression = " ^ \"\\t\" ^ ".join([_ocaml_string(name), *fields])
    return f"print_endline ({expression});;"


def _render_semantic_tail(protocol: ModuleType, nonce: str) -> list[str]:
    marker = protocol.MARKER_CONTRACT["semantic_observation"]
    lines = [
        "(* Exact ten-line semantic-v3 session; no bare marker relabelling. *)",
    ]
    for index, theorem_name in enumerate(protocol.FINAL_THEOREM_NAMES):
        require(THEOREM_VALUE.fullmatch(theorem_name) is not None,
                f"unsafe theorem value name: {theorem_name}")
        suffix = f"{index:03d}"
        theorem = f"candle_pristine_theorem_{suffix}"
        theorem_identity = f"candle_pristine_theorem_identity_{suffix}"
        hypotheses = f"candle_pristine_hypotheses_{suffix}"
        conclusion = f"candle_pristine_conclusion_{suffix}"
        axioms = f"candle_pristine_axioms_{suffix}"
        lines.extend([
            f"let {theorem} = {theorem_name};;",
            (
                f"let {theorem_identity},{hypotheses},{conclusion} = "
                f"candle_s1_theorem_parts {theorem};;"
            ),
            f"let {axioms} = candle_s1_global_axioms ();;",
            _line_call(marker, [
                _ocaml_string("THEOREM"), _ocaml_string(nonce),
                _ocaml_string(str(index)),
                f"candle_s1_hex {_ocaml_string(theorem_name)}",
                f"candle_s1_hex {theorem_identity}",
                f"candle_s1_hex {hypotheses}",
                f"candle_s1_hex {conclusion}",
                f"candle_s1_hex {axioms}",
                f"string_of_int (List.length (hyp {theorem}))",
                "string_of_int (List.length (axioms ()))",
            ]),
        ])
    lines.extend([
        (
            "let candle_pristine_kernel_state,candle_pristine_type_constants,"
            "candle_pristine_term_constants,candle_pristine_definitions,"
            "candle_pristine_global_axioms = candle_s1_kernel_state_parts ();;"
        ),
        _line_call(marker, [
            _ocaml_string("POST_STATE"), _ocaml_string(nonce),
            "candle_s1_hex candle_pristine_kernel_state",
            "candle_s1_hex candle_pristine_type_constants",
            "candle_s1_hex candle_pristine_term_constants",
            "candle_s1_hex candle_pristine_definitions",
            "candle_s1_hex candle_pristine_global_axioms",
            "string_of_int (List.length (types ()))",
            "string_of_int (List.length (constants ()))",
            "string_of_int (List.length (definitions ()))",
            "string_of_int (List.length (axioms ()))",
        ]),
    ])
    for index, theorem_name in enumerate(protocol.FINAL_THEOREM_NAMES):
        digest = f"candle_pristine_dependency_{index:03d}"
        lines.extend([
            f"let {digest} = Serialization.full_digest_thm {theorem_name};;",
            f"candle_pristine_require_lower_hex32 {digest};;",
            _line_call(marker, [
                _ocaml_string("DEPENDENCY"), _ocaml_string(nonce),
                _ocaml_string(str(index)),
                f"candle_s1_hex {_ocaml_string(theorem_name)}", digest,
            ]),
        ])
    lines.append(_line_call(marker, [
        _ocaml_string("COMPLETE"), _ocaml_string(nonce),
        _ocaml_string(protocol.FINAL_BOUNDARY_ID),
        _ocaml_string(str(len(protocol.FINAL_THEOREM_NAMES))),
        _ocaml_string(str(len(protocol.FINAL_THEOREM_NAMES))),
    ]))
    return lines


def _render_source(
    plan: dict[str, Any], source_records: list[dict[str, Any]],
    protocol: ModuleType,
) -> bytes:
    nonce = plan["session_nonce"]
    markers = protocol.MARKER_CONTRACT
    project_root = plan["authority"]["repositories"]["project"]["path"]
    flyspeck_root = plan["authority"]["repositories"]["flyspeck"]["path"]
    strictbuild = f"{flyspeck_root}/text_formalization/build/strictbuild.hl"
    final_target = f"{project_root}/candle/flyspeck_l2_target.ml"
    serializer = f"{project_root}/candle/fingerprint.ml"

    serializer_authority = plan["authority"]["inputs"]["serializer"]
    source_records = [*source_records, {
        "logical_source": protocol.SERIALIZER_SOURCE,
        "basename": PurePosixPath(serializer_authority["path"]).name,
        "bytes": serializer_authority["bytes"],
        "sha256": serializer_authority["sha256"],
        "md5": serializer_authority["md5"],
    }]
    identity_pairs = [(record["basename"], record["md5"])
                      for record in source_records]
    require(len(identity_pairs) == len(set(identity_pairs)),
            "serializer creates an ambiguous stock loader identity")

    lines = [
        "(* Generated pristine direct-reference request; raw and unapproved. *)",
        "let candle_pristine_serialization_environment_absent =",
        "  try let _ = Sys.getenv \"FLYSPECK_SERIALIZATION\" in false",
        "  with Not_found -> true;;",
        "if not candle_pristine_serialization_environment_absent then",
        "  failwith \"forbidden serialization environment\";;",
        "let candle_pristine_nonce = " + _ocaml_string(nonce) + ";;",
        "let candle_pristine_event_index = ref 0;;",
        "let candle_pristine_lp_success_count = ref 0;;",
        "let candle_pristine_source_identities = [",
    ]
    for record in source_records:
        lines.append(
            "  ((" + _ocaml_string(record["basename"]) + "," +
            _ocaml_string(record["md5"]) + "),(" +
            _ocaml_string(record["logical_source"]) + "," +
            _ocaml_string(record["basename"]) + "," +
            str(record["bytes"]) + "," + _ocaml_string(record["sha256"]) +
            "," + _ocaml_string(record["md5"]) + "));"
        )
    lines.extend([
        "];;",
        "let candle_pristine_lookup_source (basename,digest) =",
        "  try List.assoc (basename,Digest.to_hex digest)",
        "      candle_pristine_source_identities",
        "  with Not_found -> failwith (\"unsupported native loader identity: \" ^",
        "    basename ^ \"/\" ^ Digest.to_hex digest);;",
        "let rec candle_pristine_ledger_delta accumulated current previous =",
        "  if current = previous then accumulated else",
        "  match current with",
        "  | [] -> failwith \"stock loaded_files ledger is not append-only\"",
        "  | identity::tail ->",
        "      candle_pristine_ledger_delta (identity::accumulated) tail previous;;",
        "let candle_pristine_previous_loaded_files = ref [];;",
        "let candle_pristine_emit_native phase action =",
        "  let current = !loaded_files in",
        "  let delta = candle_pristine_ledger_delta [] current",
        "      !candle_pristine_previous_loaded_files in",
        "  let emit identity =",
        "    let logical,basename,bytes,sha256,md5 =",
        "      candle_pristine_lookup_source identity in",
        "    let action_field = match action with None -> \"-\"",
        "      | Some index -> string_of_int index in",
        "    print_endline (" + _ocaml_string(markers["native_load"]) +
        " ^ \"\\t\" ^ candle_pristine_nonce ^ \"\\t\" ^",
        "      string_of_int !candle_pristine_event_index ^ \"\\t\" ^ phase ^",
        "      \"\\t\" ^ action_field ^ \"\\t\" ^ logical ^ \"\\t\" ^",
        "      basename ^ \"\\t\" ^ string_of_int bytes ^ \"\\t\" ^",
        "      sha256 ^ \"\\t\" ^ md5);",
        "    incr candle_pristine_event_index in",
        "  List.iter emit delta; candle_pristine_previous_loaded_files := current;;",
        "let candle_pristine_lower_hex character =",
        "  (character >= '0' && character <= '9') ||",
        "  (character >= 'a' && character <= 'f');;",
        "let candle_pristine_require_lower_hex32 value =",
        "  if String.length value <> 32 then failwith \"malformed dependency digest\"",
        "  else for index = 0 to 31 do",
        "    if not (candle_pristine_lower_hex value.[index]) then",
        "      failwith \"malformed dependency digest\"",
        "  done;;",
        _line_call(markers["session_start"], [
            "candle_pristine_nonce",
            _ocaml_string(str(plan["reference_ordinal"])),
            _ocaml_string(plan["boundary_id"]),
        ]),
        "candle_pristine_emit_native \"bootstrap\" None;;",
        "loadt " + _ocaml_string(strictbuild) + ";;",
        "candle_pristine_emit_native \"bootstrap\" None;;",
        "let candle_pristine_actions = [|",
    ])
    for action in plan["actions"]["records"]:
        lines.append(
            "  (" + _ocaml_string(action["target"]) + "," +
            _ocaml_string(action["selected_source"]) + "," +
            _ocaml_string(action["original_sha256"]) + ");"
        )
    lines.extend([
        "|];;",
        "let candle_pristine_build_sequence =",
        "  Array.of_list Build.build_sequence_full;;",
        "if Array.length candle_pristine_actions <> 297 ||",
        "   Array.length candle_pristine_build_sequence <> 297 then",
        "  failwith \"unexpected pristine action count\";;",
        "let candle_pristine_run_action index =",
        "  let target,logical,sha256 = candle_pristine_actions.(index) in",
        "  if candle_pristine_build_sequence.(index) <> target then",
        "    failwith \"Build.build_sequence_full differs from request plan\";",
        "  flyspeck_needs target;",
        "  candle_pristine_emit_native \"action\" (Some index);",
        "  print_endline (" + _ocaml_string(markers["action_complete"]) +
        " ^ \"\\t\" ^ candle_pristine_nonce ^ \"\\t\" ^",
        "    string_of_int index ^ \"\\t\" ^ logical ^ \"\\t\" ^ sha256);;",
        "let rec candle_pristine_run_range index final =",
        "  if index <= final then (candle_pristine_run_action index;",
        "    candle_pristine_run_range (index + 1) final);;",
        "candle_pristine_run_range 0 177;;",
        "let candle_pristine_lp_inputs = [",
    ])
    lp_basenames: set[str] = set()
    for record in plan["lp_certificate_inputs"]["records"]:
        basename = PurePosixPath(record["relative"]).name
        require(basename not in lp_basenames,
                f"ambiguous LP input basename: {basename}")
        lp_basenames.add(basename)
        lines.append(
            "  (" + _ocaml_string(basename) + ",(" + str(record["index"]) +
            "," + _ocaml_string(record["class"]) + "," +
            _ocaml_string(record["relative"]) + "," + str(record["bytes"]) +
            "," + _ocaml_string(record["sha256"]) + "));"
        )
    lines.extend([
        "];;",
        "let candle_pristine_lp_seen = Array.make 39 false;;",
        "module Candle_pristine_original_lp_certificate = Lp_certificate;;",
        "module Lp_certificate = struct",
        "  include Candle_pristine_original_lp_certificate",
        "  let read_lp_certificates filename =",
        "    let result =",
        "      Candle_pristine_original_lp_certificate.read_lp_certificates",
        "        filename in",
        "    let input_index,class_name,relative,bytes,sha256 =",
        "      try List.assoc (Filename.basename filename) candle_pristine_lp_inputs",
        "      with Not_found -> failwith \"unplanned LP certificate input\" in",
        "    if candle_pristine_lp_seen.(input_index) then",
        "      failwith \"duplicate LP certificate input\";",
        "    candle_pristine_lp_seen.(input_index) <- true;",
        "    print_endline (" + _ocaml_string(markers["lp_success"]) +
        " ^ \"\\t\" ^ candle_pristine_nonce ^ \"\\t\" ^",
        "      string_of_int !candle_pristine_lp_success_count ^ \"\\t\" ^",
        "      \"184\" ^ \"\\t\" ^ string_of_int input_index ^ \"\\t\" ^",
        "      class_name ^ \"\\t\" ^ relative ^ \"\\t\" ^",
        "      string_of_int bytes ^ \"\\t\" ^ sha256 ^ \"\\t1\");",
        "    incr candle_pristine_lp_success_count; result",
        "end;;",
        "candle_pristine_run_range 178 183;;",
        "Verify_all.cert_dir := " + _ocaml_string(
            plan["retained_input_artifact_root"] + "/formal_lp/glpk/binary"
        ) + ";;",
        "candle_pristine_run_range 184 296;;",
        "if !candle_pristine_lp_success_count <> 39 ||",
        "   Array.exists (fun observed -> not observed) candle_pristine_lp_seen then",
        "  failwith \"incomplete LP certificate success stream\";;",
        "loadt " + _ocaml_string(final_target) + ";;",
        "candle_pristine_emit_native \"post-action\" None;;",
        "loadt " + _ocaml_string(serializer) + ";;",
        "candle_pristine_emit_native \"post-action\" None;;",
    ])
    lines.extend(_render_semantic_tail(protocol, nonce))
    lines.extend([
        _line_call(markers["session_complete"], [
            "candle_pristine_nonce", _ocaml_string(plan["boundary_id"]),
            _ocaml_string(str(protocol.FINAL_ACTION_COUNT)),
            _ocaml_string("39"),
            "string_of_int !candle_pristine_event_index",
        ]),
        "flush stdout;;",
    ])
    source = ("\n".join(lines) + "\n").encode("ascii")
    require(b"CANDLE_FINGERPRINT_V2" not in source and
            b"CANDLE_STATE_FINGERPRINT_V2" not in source and
            b"candle_s1_emit_fingerprint" not in source and
            b"candle_s1_emit_state_fingerprint" not in source,
            "request source attempts bare fingerprint-marker relabelling")
    return source


def generate_unapproved_raw_request(
    plan: object, source_inventory: object,
) -> tuple[bytes, dict[str, Any]]:
    """Return exact ``request.ml`` bytes and the validated raw request value.

    The result is a request prerequisite only.  It is not an authenticated
    execution, source rederivation, coverage projection, candidate or approval.
    """

    protocol = _protocol()
    try:
        validated_plan = protocol.validate_raw_plan(plan)
    except protocol.ProtocolError as error:
        raise RequestGenerationError(f"invalid raw plan: {error}") from error
    source_records = _validate_source_inventory(
        source_inventory, validated_plan, protocol,
    )
    source = _render_source(validated_plan, source_records, protocol)
    request = {
        "schema": protocol.RAW_PROTOCOL_SCHEMA,
        "kind": protocol.REQUEST_KIND,
        "role": validated_plan["role"],
        "reference_ordinal": validated_plan["reference_ordinal"],
        "nonce_kind": validated_plan["nonce_kind"],
        "session_nonce": validated_plan["session_nonce"],
        "boundary_id": validated_plan["boundary_id"],
        "plan": protocol.content_record(validated_plan),
        "request_source": {
            "path": REQUEST_SOURCE_PATH,
            "bytes": len(source),
            "sha256": hashlib.sha256(source).hexdigest(),
        },
        "entrypoint_sequence": copy.deepcopy(list(protocol.ENTRYPOINT_SEQUENCE)),
        "marker_contract": copy.deepcopy(protocol.MARKER_CONTRACT),
        "action_count": protocol.FINAL_ACTION_COUNT,
        "serialization_environment": copy.deepcopy(
            validated_plan["serialization_environment"]
        ),
        "fresh_process_replay_from_action_zero": True,
        "process_state_checkpoint": None,
        "retained_stdout_max_bytes": validated_plan[
            "retained_stdout_max_bytes"
        ],
        "retained_stderr_max_bytes": validated_plan[
            "retained_stderr_max_bytes"
        ],
        "retained_input_artifact_root": validated_plan[
            "retained_input_artifact_root"
        ],
        "approval_included": False,
        "pft_used": False,
        "s2_s3_evidence": False,
    }
    try:
        protocol.validate_raw_request(request, validated_plan)
    except protocol.ProtocolError as error:
        raise RequestGenerationError(
            f"generated raw request is invalid: {error}"
        ) from error
    return source, request
